### ISSUE TITLE
[Request] WEB Server Implementation PHP and Apache

### ISSUE THREAD

**Issue by d3athbl0w** [fIyingPhoenix/TrionControlPanel#8]
First of all, I thank you for such a great tool and its developers.

I would like to make this suggestion so that Apache and PHP 8.1+ are implemented but that the modules and extensions are configurable from the control panel, also, it would also be good to implement an option to download the user's preferred version of PHP and the user's preferred version of MySQL

**Comment by fIyingPhoenix** [comment]
>First of all, I thank you for such a great tool and its developers. 

Its just a way for me to learn new stuff. :)

>I would like to make this suggestion so that Apache and PHP 8.1+ are implemented but that the modules and extensions are configurable from the control panel, also, it would also be good to implement an option to download the user's preferred version of PHP and the user's preferred version of MySQL

I have a web based Control Panel, its using .NET Core as the backend, with C# as language. i don't need , and i dont want to implement PHP or Apache because .Net is using there own Hosting client to run the website. But of course you can use Nginx or Apache Proxy to redirect to the webiste. The Website is still work in progress and dose need a lot of love and work but im on it in my free time. The Desktop client is Windows only and got to life because  i do like to Play with WoW emulators myself, and i was annoyed from the many windows opened, always downloading mysql when i did a new VM, never notice if a server crashed or if i wanted to see how much ram it used, etc.. i can look into it. I can't promise anything because it was never intended for live use. 

I'm always open to new ideas and I appreciate it.
